CREATE TABLE MEMBER(
	MID VARCHAR2(50) PRIMARY KEY,
	MPASS VARCHAR2(200) NOT NULL,
	MNAME NVARCHAR2(200) NOT NULL,
	MREGDATE TIMESTAMP DEFAULT SYSTIMESTAMP,
	MDELYN CHAR(1) DEFAULT 'N'
);

DROP TABLE BOARD;

CREATE TABLE BOARD (
	BID NUMBER PRIMARY KEY,
	BNAME NVARCHAR2(20) NOT NULL,
	BREGDATE TIMESTAMP DEFAULT SYSTIMESTAMP,
	BDELYN CHAR(1) DEFAULT 'N'
);

CREATE SEQUENCE SEQ_BOARD;

CREATE TABLE ARTICLE(
	AID NUMBER PRIMARY KEY,
	ATITLE NVARCHAR2(2000) NOT NULL,
	ACONTENT NVARCHAR2(2000),
	AREGDATE TIMESTAMP DEFAULT SYSTIMESTAMP,
	ACOUNT NUMBER DEFAULT 0,
	AFCOUNT NUMBER DEFAULT 0,
	ADELYN CHAR(1) DEFAULT 'N',
	MID VARCHAR2(50),
	BID NUMBER,
	FOREIGN KEY (MID) REFERENCES MEMBER(MID),
	FOREIGN KEY (BID) REFERENCES BOARD(BID)
);

CREATE SEQUENCE SEQ_ARTICLE;

CREATE TABLE REPLY(
	RID NUMBER PRIMARY KEY,
	RCONTENT NVARCHAR2(2000) NOT NULL,
	RREGDATE TIMESTAMP DEFAULT SYSTIMESTAMP,
	RDELYN CHAR(1) DEFAULT 'N',
	MID VARCHAR2(50),
	AID NUMBER,
	FOREIGN KEY (MID) REFERENCES MEMBER(MID),
	FOREIGN KEY (AID) REFERENCES ARTICLE(AID)
);

CREATE SEQUENCE SEQ_REPLY;

CREATE TABLE AFILE(
	AFID NUMBER PRIMARY KEY,
	AFSFNAME NVARCHAR2(500),
	AFCFNAME NVARCHAR2(500),
	AFREGDATE TIMESTAMP DEFAULT SYSTIMESTAMP,
	AFDELYN CHAR(1) DEFAULT 'N',
	MID VARCHAR2(50),
	AID NUMBER,
	FOREIGN KEY (MID) REFERENCES MEMBER(MID),
	FOREIGN KEY (AID) REFERENCES ARTICLE(AID)
);

CREATE SEQUENCE SEQ_AFILE;
