CREATE TABLE AUTHOR(
	AUTHOR_ID NUMBER PRIMARY KEY,
	AUTHOR_NAME NVARCHAR2(200)
);

CREATE SEQUENCE SEQ_AUTHOR;

INSERT INTO AUTHOR VALUES(SEQ_AUTHOR.NEXTVAL, '홍길동');
INSERT INTO AUTHOR VALUES(SEQ_AUTHOR.NEXTVAL, '강감찬');

CREATE TABLE COMM(
	COMM_ID NUMBER PRIMARY KEY,
	COMM_TITLE NVARCHAR2(500),
	COMM_CONTENT NVARCHAR2(2000),
	BLOG_ID NUMBER,
	FOREIGN KEY(BLOG_ID) REFERENCES BLOG(BLOG_ID)	
);

CREATE SEQUENCE SEQ_COMM;

INSERT INTO COMM VALUES(SEQ_COMM.NEXTVAL, '댓글제목1', '댓글내용1', 1);
INSERT INTO COMM VALUES(SEQ_COMM.NEXTVAL, '댓글제목2', '댓글내용2', 1);
INSERT INTO COMM VALUES(SEQ_COMM.NEXTVAL, '댓글제목3', '댓글내용3', 1);
INSERT INTO COMM VALUES(SEQ_COMM.NEXTVAL, '댓글제목4', '댓글내용4', 2);
INSERT INTO COMM VALUES(SEQ_COMM.NEXTVAL, '댓글제목5', '댓글내용5', 2);
INSERT INTO COMM VALUES(SEQ_COMM.NEXTVAL, '댓글제목6', '댓글내용6', 2);
INSERT INTO COMM VALUES(SEQ_COMM.NEXTVAL, '댓글제목5', '댓글내용5', 2);
INSERT INTO COMM VALUES(SEQ_COMM.NEXTVAL, '댓글제목6', '댓글내용6', 2);

CREATE TABLE BLOG(
	BLOG_ID NUMBER PRIMARY KEY,
	BLOG_NAME NVARCHAR2(200),
	BLOG_TITLE NVARCHAR2(500),
	AUTHOR_ID NUMBER,
	FOREIGN KEY(AUTHOR_ID) REFERENCES AUTHOR(AUTHOR_ID)
);

CREATE SEQUENCE SEQ_BLOG;

INSERT INTO BLOG VALUES(SEQ_BLOG.NEXTVAL, '블로그1', '블로그제목1', 1);
INSERT INTO BLOG VALUES(SEQ_BLOG.NEXTVAL, '블로그2', '블로그제목2', 1);
INSERT INTO BLOG VALUES(SEQ_BLOG.NEXTVAL, '블로그3', '블로그제목3', 2);
INSERT INTO BLOG VALUES(SEQ_BLOG.NEXTVAL, '블로그4', '블로그제목4', 2);
INSERT INTO BLOG VALUES(SEQ_BLOG.NEXTVAL, '블로그5', '블로그제목5', 2);

COMMIT;

SELECT * FROM BLOG;
SELECT * FROM COMM;
SELECT * FROM AUTHOR;


































